# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTMainConfig.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WizardConfig(object):
    def setupUi(self, WizardConfig):
        WizardConfig.setObjectName(_fromUtf8("WizardConfig"))
        WizardConfig.resize(671, 550)
        WizardConfig.setMinimumSize(QtCore.QSize(318, 550))
        WizardConfig.setMaximumSize(QtCore.QSize(524287, 524287))
        WizardConfig.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/iconos/config.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        WizardConfig.setWindowIcon(icon)
        WizardConfig.setWizardStyle(QtGui.QWizard.AeroStyle)
        WizardConfig.setOptions(QtGui.QWizard.IgnoreSubTitles)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wizardPage1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Logo = QtGui.QLabel(self.wizardPage1)
        self.Logo.setText(_fromUtf8(""))
        self.Logo.setPixmap(QtGui.QPixmap(_fromUtf8(":/logo/LogoLogin.png")))
        self.Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.Logo.setObjectName(_fromUtf8("Logo"))
        self.verticalLayout.addWidget(self.Logo)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        WizardConfig.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_BD = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_BD.setObjectName(_fromUtf8("groupBox_BD"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_BD)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_BD)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox_UbicacionBD = QtGui.QGroupBox(self.groupBox_BD)
        self.groupBox_UbicacionBD.setTitle(_fromUtf8(""))
        self.groupBox_UbicacionBD.setObjectName(_fromUtf8("groupBox_UbicacionBD"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_UbicacionBD)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_Remota = QtGui.QRadioButton(self.groupBox_UbicacionBD)
        self.radioButton_Remota.setObjectName(_fromUtf8("radioButton_Remota"))
        self.horizontalLayout.addWidget(self.radioButton_Remota)
        self.radioButton_Local = QtGui.QRadioButton(self.groupBox_UbicacionBD)
        self.radioButton_Local.setChecked(True)
        self.radioButton_Local.setObjectName(_fromUtf8("radioButton_Local"))
        self.horizontalLayout.addWidget(self.radioButton_Local)
        self.gridLayout_2.addWidget(self.groupBox_UbicacionBD, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_BD)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_DireccionBD = QtGui.QLineEdit(self.groupBox_BD)
        self.lineEdit_DireccionBD.setMaxLength(100)
        self.lineEdit_DireccionBD.setObjectName(_fromUtf8("lineEdit_DireccionBD"))
        self.gridLayout_2.addWidget(self.lineEdit_DireccionBD, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_BD)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_UsuarioBD = QtGui.QLineEdit(self.groupBox_BD)
        self.lineEdit_UsuarioBD.setMaxLength(100)
        self.lineEdit_UsuarioBD.setObjectName(_fromUtf8("lineEdit_UsuarioBD"))
        self.gridLayout_2.addWidget(self.lineEdit_UsuarioBD, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_BD)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_ClaveBD = QtGui.QLineEdit(self.groupBox_BD)
        self.lineEdit_ClaveBD.setMaxLength(100)
        self.lineEdit_ClaveBD.setObjectName(_fromUtf8("lineEdit_ClaveBD"))
        self.gridLayout_2.addWidget(self.lineEdit_ClaveBD, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_BD, 1, 0, 1, 2)
        self.groupBox_Tipo = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_Tipo.setObjectName(_fromUtf8("groupBox_Tipo"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_Tipo)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        self.radioButton_Cliente = QtGui.QRadioButton(self.groupBox_Tipo)
        self.radioButton_Cliente.setObjectName(_fromUtf8("radioButton_Cliente"))
        self.gridLayout_5.addWidget(self.radioButton_Cliente, 0, 2, 1, 1)
        self.radioButton_Server = QtGui.QRadioButton(self.groupBox_Tipo)
        self.radioButton_Server.setChecked(True)
        self.radioButton_Server.setObjectName(_fromUtf8("radioButton_Server"))
        self.gridLayout_5.addWidget(self.radioButton_Server, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 3, 1, 1)
        self.Clear = QtGui.QPushButton(self.groupBox_Tipo)
        self.Clear.setMaximumSize(QtCore.QSize(10, 16777215))
        self.Clear.setText(_fromUtf8(""))
        self.Clear.setObjectName(_fromUtf8("Clear"))
        self.gridLayout_5.addWidget(self.Clear, 0, 4, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_Tipo, 0, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_DireccionSMTP = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_DireccionSMTP.setMaxLength(500)
        self.lineEdit_DireccionSMTP.setObjectName(_fromUtf8("lineEdit_DireccionSMTP"))
        self.gridLayout_3.addWidget(self.lineEdit_DireccionSMTP, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.lineEdit_PuertoSMTP = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_PuertoSMTP.setMaxLength(7)
        self.lineEdit_PuertoSMTP.setPlaceholderText(_fromUtf8(""))
        self.lineEdit_PuertoSMTP.setObjectName(_fromUtf8("lineEdit_PuertoSMTP"))
        self.gridLayout_3.addWidget(self.lineEdit_PuertoSMTP, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_UsuarioCorreo = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_UsuarioCorreo.setMaxLength(500)
        self.lineEdit_UsuarioCorreo.setPlaceholderText(_fromUtf8(""))
        self.lineEdit_UsuarioCorreo.setObjectName(_fromUtf8("lineEdit_UsuarioCorreo"))
        self.gridLayout_3.addWidget(self.lineEdit_UsuarioCorreo, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEdit_ClaveCorreo = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_ClaveCorreo.setMaxLength(500)
        self.lineEdit_ClaveCorreo.setObjectName(_fromUtf8("lineEdit_ClaveCorreo"))
        self.gridLayout_3.addWidget(self.lineEdit_ClaveCorreo, 3, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_5, 4, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lineEdit_ServerWeb = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ServerWeb.setObjectName(_fromUtf8("lineEdit_ServerWeb"))
        self.gridLayout_6.addWidget(self.lineEdit_ServerWeb, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 5, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_SMSLongitud = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_SMSLongitud.setMaxLength(3)
        self.lineEdit_SMSLongitud.setObjectName(_fromUtf8("lineEdit_SMSLongitud"))
        self.gridLayout.addWidget(self.lineEdit_SMSLongitud, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_PrefijosSMS = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_PrefijosSMS.setMaxLength(500)
        self.lineEdit_PrefijosSMS.setObjectName(_fromUtf8("lineEdit_PrefijosSMS"))
        self.gridLayout.addWidget(self.lineEdit_PrefijosSMS, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_PruebaRSMS = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_PruebaRSMS.setMaxLength(500)
        self.lineEdit_PruebaRSMS.setObjectName(_fromUtf8("lineEdit_PruebaRSMS"))
        self.gridLayout.addWidget(self.lineEdit_PruebaRSMS, 2, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 4, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.p1 = QtGui.QLineEdit(self.groupBox_2)
        self.p1.setEchoMode(QtGui.QLineEdit.NoEcho)
        self.p1.setObjectName(_fromUtf8("p1"))
        self.verticalLayout_2.addWidget(self.p1)
        self.p2 = QtGui.QLineEdit(self.groupBox_2)
        self.p2.setEchoMode(QtGui.QLineEdit.NoEcho)
        self.p2.setObjectName(_fromUtf8("p2"))
        self.verticalLayout_2.addWidget(self.p2)
        self.gridLayout_4.addWidget(self.groupBox_2, 5, 1, 2, 1)
        self.pushButton_GenerarConfig = QtGui.QPushButton(self.wizardPage2)
        self.pushButton_GenerarConfig.setObjectName(_fromUtf8("pushButton_GenerarConfig"))
        self.gridLayout_4.addWidget(self.pushButton_GenerarConfig, 6, 0, 1, 1)
        WizardConfig.addPage(self.wizardPage2)

        self.retranslateUi(WizardConfig)
        QtCore.QMetaObject.connectSlotsByName(WizardConfig)
        WizardConfig.setTabOrder(self.radioButton_Server, self.radioButton_Cliente)
        WizardConfig.setTabOrder(self.radioButton_Cliente, self.radioButton_Remota)
        WizardConfig.setTabOrder(self.radioButton_Remota, self.radioButton_Local)
        WizardConfig.setTabOrder(self.radioButton_Local, self.lineEdit_DireccionBD)
        WizardConfig.setTabOrder(self.lineEdit_DireccionBD, self.lineEdit_UsuarioBD)
        WizardConfig.setTabOrder(self.lineEdit_UsuarioBD, self.lineEdit_ClaveBD)
        WizardConfig.setTabOrder(self.lineEdit_ClaveBD, self.lineEdit_SMSLongitud)
        WizardConfig.setTabOrder(self.lineEdit_SMSLongitud, self.lineEdit_PrefijosSMS)
        WizardConfig.setTabOrder(self.lineEdit_PrefijosSMS, self.lineEdit_PruebaRSMS)
        WizardConfig.setTabOrder(self.lineEdit_PruebaRSMS, self.lineEdit_DireccionSMTP)
        WizardConfig.setTabOrder(self.lineEdit_DireccionSMTP, self.lineEdit_PuertoSMTP)
        WizardConfig.setTabOrder(self.lineEdit_PuertoSMTP, self.lineEdit_UsuarioCorreo)
        WizardConfig.setTabOrder(self.lineEdit_UsuarioCorreo, self.lineEdit_ClaveCorreo)
        WizardConfig.setTabOrder(self.lineEdit_ClaveCorreo, self.lineEdit_ServerWeb)

    def retranslateUi(self, WizardConfig):
        WizardConfig.setWindowTitle(_translate("WizardConfig", "Configurar Estacion 365Connect", None))
        self.groupBox_BD.setTitle(_translate("WizardConfig", "Configuracion de Base de Datos", None))
        self.label.setText(_translate("WizardConfig", "Ubicacion", None))
        self.radioButton_Remota.setText(_translate("WizardConfig", "Remota o Instancia", None))
        self.radioButton_Local.setText(_translate("WizardConfig", "Local", None))
        self.label_3.setText(_translate("WizardConfig", "Direccion", None))
        self.lineEdit_DireccionBD.setPlaceholderText(_translate("WizardConfig", "192.168.0.20", None))
        self.label_4.setText(_translate("WizardConfig", "Usuario", None))
        self.label_5.setText(_translate("WizardConfig", "Contrasena", None))
        self.groupBox_Tipo.setTitle(_translate("WizardConfig", "Tipo", None))
        self.radioButton_Cliente.setText(_translate("WizardConfig", "Cliente", None))
        self.radioButton_Server.setText(_translate("WizardConfig", "Server", None))
        self.groupBox_5.setTitle(_translate("WizardConfig", "Configuracion de AlertMail", None))
        self.lineEdit_DireccionSMTP.setText(_translate("WizardConfig", "smtp.gmail.com", None))
        self.label_11.setText(_translate("WizardConfig", "Direccion SMTP", None))
        self.label_13.setText(_translate("WizardConfig", "Usuario Correo", None))
        self.lineEdit_PuertoSMTP.setText(_translate("WizardConfig", "587", None))
        self.label_12.setText(_translate("WizardConfig", "Puerto SMTP", None))
        self.label_6.setText(_translate("WizardConfig", "Clave Correo", None))
        self.groupBox.setTitle(_translate("WizardConfig", "Otros", None))
        self.label_2.setText(_translate("WizardConfig", "ServerWeb", None))
        self.groupBox_3.setTitle(_translate("WizardConfig", "Configuracion de AlertSMS", None))
        self.label_7.setText(_translate("WizardConfig", "Longitud Permitida", None))
        self.lineEdit_SMSLongitud.setText(_translate("WizardConfig", "11", None))
        self.label_8.setText(_translate("WizardConfig", "Prefijos Permitidos", None))
        self.lineEdit_PrefijosSMS.setText(_translate("WizardConfig", "0414,0424,0416,0426,0412", None))
        self.lineEdit_PrefijosSMS.setPlaceholderText(_translate("WizardConfig", "Sin espacios separados por (,) Ej. 0414,0416", None))
        self.label_9.setText(_translate("WizardConfig", "# Prueba Rapida", None))
        self.lineEdit_PruebaRSMS.setText(_translate("WizardConfig", "04125556655,04126669955", None))
        self.lineEdit_PruebaRSMS.setPlaceholderText(_translate("WizardConfig", "Sin espacios separados por (,)", None))
        self.groupBox_2.setTitle(_translate("WizardConfig", "Parametros", None))
        self.pushButton_GenerarConfig.setText(_translate("WizardConfig", "Generar Configuracion", None))

import recursosconfig_rc
